---
title: "Hidrogramas"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE,warning = FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(rmarkdown)
library(knitr)
```

## Hidrogramas diarios

```{r}
qobs <- readRDS("./docs/data/qobs_previo_mm.RDS")
# chico, cabecera, ruta3, bypass

library(xts)
library(dygraphs)
qs = xts(x = qobs[,c("SA01","SA02","SA03","SA04")], order.by = qobs$Date)
dygraph(qs) %>%
  dyRangeSelector()%>% 
  dyOptions(colors = c("blue","red","green","black"))
```


## Curvas de duración de caudales

```{r}
qseq = seq(min(c(qobs$SA01,qobs$SA02,qobs$SA03,qobs$SA04),na.rm=T),
           max(c(qobs$SA01,qobs$SA02,qobs$SA03,qobs$SA04),na.rm=T),
           0.01)

ec01 = ecdf(qobs$SA01)
ec02 = ecdf(qobs$SA02)
ec03 = ecdf(qobs$SA03)
ec04 = ecdf(qobs$SA04)

qdur = data.frame(caudal = qseq,
                  SA01 = ec01(qseq),
                  SA02 = ec02(qseq),
                  SA03 = ec03(qseq),
                  SA04 = ec04(qseq))
library(plotly)

PT = plot_ly(data = qdur, x=~caudal,y=~SA01, type='scatter', 
             mode='lines', name="Chico",
             #marker=list(color='black', size=0),
             width=750, height=500)
PT = PT %>% add_trace(data = qdur, x=~caudal,y=~SA02, name="Cabecera")
PT = PT %>% add_trace(data = qdur, x=~caudal,y=~SA03, name="Ruta 3")
PT = PT %>% add_trace(data = qdur, x=~caudal,y=~SA04, name="ByPass")
PT <- layout(PT, 
             xaxis = list(title="Escorrentía (mm)",type = "log"),
             yaxis = list(title="Probabilidad de no excedencia"),
             margin=list(l=50,r=50,b=50,t=80,pad=4)
)

PT
```



## Datos de escorrentía

```{r}
qtab = qobs
qtab[,2:5] = round(qobs[,2:5],3)
qtab %>%
    DT::datatable(caption = "Escorentía (mm)",
                extensions = 'Buttons',
                options = list(bLengthChange = FALSE,
                               dom = 'Blfrtip',
                               buttons = c('csv', 'pdf'),
                               lengthMenu = list(c(5,10,50,-1))),
                colnames = c("fecha", "Chico","Cabecera","Ruta3","ByPass" ), 
                width = 600, height = 300)
```

